myrestaurant/inventory/urls.py
from django.urls import path

from .models import *
from . import views

urlpatterns = [
    path("login/", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    
    path("home/", views.home, name="home"),
    
    path("ingredient/list", views.IngredientListView.as_view(), name='ingredients'),
    path("ingredient/create/", views.IngredientCreateView.as_view(), name='add_ingredient'),
    path("ingredient/update/<int:pk>", views.IngredientUpdateView.as_view(), name="update_ingredient"),
    
    path('recipe/', views.RecipeRequirementListView.as_view(), name="recipe"),
    path('recipe/create/', views.RecipeRequirementCreateView.as_view(), name='add_recipe_requirement'),
    
    path("menu/list", views.MenuItemListView.as_view(), name='menu'),
    path("menu/create/", views.MenuItemCreateView.as_view(), name="add_menu_item"),
    
    path("purchases/list", views.PurchaseListView.as_view(), name='purchases'),
    path("purchase/create/", views.PurchaseCreateView.as_view(), name='add_purchase'),
    path("reports/", views.ReportsView.as_view(), name='reports'),
]

myrestaurant/myrestaurant/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('inventory.urls')),
    ]

myrestaurant/inventory/models.py
from django.db import models
import datetime
from django.urls import reverse

# Create your models here.
class Ingredient(models.Model):
    name = models.CharField(max_length=30, null=False)
    quantity = models.DecimalField(max_digits=6, decimal_places=1)
    TBSP = 'tbsp'
    LBS = 'lbs'
    GRAMMS = 'gramms'
    EGGS = 'eggs'
    OUNCES = 'ounces'
    UNIT_MEASURE = [
        (TBSP, 'tbsp'), (LBS, 'lbs'), (GRAMMS, 'gramms'), (EGGS, 'eggs'), (OUNCES, 'ounces')
    ]
    unit = models.CharField(max_length=6, choices=UNIT_MEASURE, default=LBS, null=False)
    unit_price = models.DecimalField(max_digits=6, decimal_places=2)
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("ingredients")
    
    
class MenuItem(models.Model):
    title = models.CharField(max_length=30, null=False)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    
    def __str__(self):
        return self.title
    
class RecipeRequirement(models.Model):
    menu_item = models.ForeignKey(MenuItem, on_delete=models.CASCADE)
    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE)
    quantity = models.DecimalField(max_digits=6, decimal_places=2)
    
    def get_absolute_url(self):
        return reverse("home")
    

class Purchase(models.Model):
    menu_item = models.ForeignKey(MenuItem, on_delete=models.CASCADE)
    timestamp = models.DateField(default=datetime.date.today)
    
    

myrestaurant/inventory/forms.py
from django import forms
from . models import *

class IngredientForm(forms.ModelForm):
    class Meta:
        model = Ingredient
        fields = "__all__"
        
class MenuItemForm(forms.ModelForm):
    class Meta:
        model = MenuItem
        fields = "__all__"
        
class RecipeRequirementForm(forms.ModelForm):
    class Meta:
        model = RecipeRequirement
        fields = "__all__"
        
class PurchaseForm(forms.ModelForm):
    class Meta:
        model = Purchase
        fields = "__all__"

myrestaurant/inventory/views.py
from django.shortcuts import render, HttpResponse
from .models import *
from .forms import *
from django.views.generic import ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.base import TemplateView
from django.db.models import Sum
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.urls import reverse

# Create your views here.

def home(request):
    ingredients = Ingredient.objects.all()
    menu_items = MenuItem.objects.all()
    recipe_requirements = Ingredient.objects.all()
    purchases = Purchase.objects.all()
    
    context = {
        "ingredients" : ingredients,
        "menu_items" : menu_items,
        "recipe_requirements" :recipe_requirements,
        "purchases" : purchases
    }
    return render(request, 'inventory/home.html', context)

def login_view(request):
    context = {
        "login_view" : "active"
    }
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect(reverse("home"))
        else:
            HttpResponse("Invalid login and password")        
    return render(request, "registration/login.html", context)
    
def logout_view(request):
    logout(request)
    return redirect(reverse('login'))

class IngredientListView(ListView, LoginRequiredMixin):
    model = Ingredient
    template_name = "inventory/ingredients_list.html"
    
    
class IngredientCreateView(CreateView, LoginRequiredMixin):
    model = Ingredient
    template_name = "inventory/add_ingredient.html"
    form_class = IngredientForm

class IngredientUpdateView(UpdateView, LoginRequiredMixin):
    model = Ingredient
    template_name = "inventory/update_ingredient.html"
    form_class = IngredientForm

class IngredientDeleteView(DeleteView, LoginRequiredMixin):
    model = Ingredient
    template_name = "inventory/delete_ingredient.html"
    form_class = IngredientForm
    
class MenuItemListView(ListView):
    model = MenuItem
    template_name = "inventory/menu_list.html"
    
class MenuItemCreateView(CreateView, LoginRequiredMixin):
    model = MenuItem
    template_name = "inventory/add_menu_item.html"
    form_class = MenuItemForm
    
class MenuItemUpdateView(UpdateView, LoginRequiredMixin):
    model = MenuItem
    template_name = "inventory/update_menu_item.html"
    form_class = MenuItem
    
class MenuItemDeleteView(DeleteView, LoginRequiredMixin):
    model = MenuItem
    template_name = "inventory/delete_menu_item.html"
    form_class = MenuItem
    
class RecipeRequirementListView(ListView, LoginRequiredMixin):
    model = RecipeRequirementForm
    
    
class RecipeRequirementCreateView(CreateView, LoginRequiredMixin):
    model = RecipeRequirement
    template_name = "inventory/add_recipe_requirement.html"
    form_class = RecipeRequirementForm
    
class RecipeRequirementUpdateView(UpdateView, LoginRequiredMixin):
    model = RecipeRequirement
    template_name = "inventory/update_reciperequirement.html"
    form_class = RecipeRequirementForm
    
class RecipeRequirementDeleteView(DeleteView, LoginRequiredMixin):
    model = RecipeRequirement
    template_name = "inventory/delete_reciperequirement.html"
    form_class = RecipeRequirementForm
    
class PurchaseListView(ListView):
    model = Purchase
    
class PurchaseCreateView(CreateView, LoginRequiredMixin):
    model = Purchase
    template_name = "inventory/add_purchase.html"
    form_class = PurchaseForm
    
class PurchaseUpdateView(UpdateView, LoginRequiredMixin):
    model = Purchase
    template_name = "inventory/update_purchase.html"
    form_class = PurchaseForm
    
class PurchaseDeleteView(DeleteView, LoginRequiredMixin):
    model = Purchase
    template_name = "inventory/delete_purchase.html"
    form_class = PurchaseForm
    
class ReportsView(TemplateView):
    template_name = "inventory/reports.html"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        total_revenue = Purchase.objects.aggregate(total_revenue=Sum('menu_item__price'))
        context['revenue'] = total_revenue['total_revenue'] or 0
        
        total_cost = RecipeRequirement.objects.aggregate(total_cost=Sum('ingredient__unit_price'))
        context['total_cost'] = total_cost['total_cost'] or 0
        
        context['profit'] = context['revenue'] - context ['total_cost']
        
        return context

myrestaurant/inventory/templates/base.html
{% load static %} 
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <link rel="shortcut icon" type="image/x-icon" href="https://www.codecademy.com/favicon.ico">
  <link rel="stylesheet" type="text/css" href="{% static 'inventory/style.css' %}" />
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Oxygen:wght@300;400;700&display=swap" rel="stylesheet">
  <title>{% block title %}Django Delights{% endblock %}</title>
  {% block head %}{% endblock %}
</head>
<body>
  <div class="app">
  <header>
    <div class="header-first-row">
      <h1 class="title">Django Delights</h1>
      {% if user.is_authenticated %}
      <a class="logout" href="/logout">Logout</a>
      {% endif %}
    </div>
    {% if user.is_authenticated %}
      <p>Hi, {{ user.username }}!</p>
      <nav class="navbar">
        {% url 'home' as home_url %}
        {% url 'ingredients' as ingredients_url %}
        {% url 'menu' as menu_url %}
        {% url 'purchases' as purchases_url %}
        {% url 'reports' as reports_url %}
        <a class="nav-item{% if request.path == home_url %} current-page{% endif %}" href="{% url 'home' %}">Home</a>
        <a class="nav-item{% if request.path == ingredients_url %} current-page{% endif %}" href="{% url 'ingredients' %}">Ingredients</a>
        <a class="nav-item{% if request.path == menu_url %} current-page{% endif %}" href="{% url 'menu' %}">Menu</a>
        <a class="nav-item{% if request.path == purchases_url %} current-page{% endif %}" href="{% url 'purchases' %}">Purchases</a>
        <a class="nav-item{% if request.path == reports_url %} current-page{% endif %}" href="{% url 'reports' %}">Reports</a>
      </nav>
    {% endif %}
  </header>
  <main>
    {% block content %}{% endblock %}
  </main>
  </div>
</body>
</html>

myrestaurant/inventory/templates/inventory/add_ingredient.html
{% extends 'base.html' %}
{% load static %} 
{% block content %}
    <h2>Add Ingredient to Inventory</h2>
    <form method="post">
    <div>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit"/>
    </div>
    </form>
{% endblock %}

myrestaurant/inventory/templates/inventory/add_menu_item.html
{% extends 'base.html' %}
{% load static %} 
{% block content %}
    <h2>Add Item to Menu</h2>
    <form method="post">
    <div>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit"/>
    </div>
    </form>
{% endblock %}

myrestaurant/inventory/templates/inventory/add_purchase.html
{% extends 'base.html' %}
{% load static %} 
{% block content %}
    <h2>Enter a new purchase</h2>
    <form method="post">
    <div>
    {% csrf_token %}
    {{ form.as_p }}
    <p>
        <label for="menu_item">Menu item:</label>
        <select name="menu_item" id="menu_item" required>
            <option value selected>-----</option>
        {% for menu_item in menu_items %}
            <option value={{ menu_item.id }}>{{ menu_item.title }}</option>
        {% endfor %}
        </select>
    </p>
    <input type="submit" value="Submit"/>
    </div>
    </form>
{% endblock %}

myrestaurant/inventory/templates/inventory/add_recipe_requirement.html
{% extends 'base.html' %}
{% load static %} 
{% block content %}
    <h2>Add Recipe Requirement for a Menu Item</h2>
    <form method="post">
    <div>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit"/>
    </div>
    </form>
{% endblock %}

myrestaurant/inventory/templates/inventory/home.html
{% extends 'base.html' %}
{% load static %} 
{% block title %}Django Delights{% endblock %}
{% block content %}
    <div class="home">
        <div>
            <h2>Ingredients</h2>
            <table class="inventory-table">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Quantity</th>
                        <th>Unit</th>
                        <th>Unit Price</th>
                    </tr>
                </thead>
                <tbody>
                {% for ingredient in ingredients %}
                    <tr>
                        <td>{{ ingredient.name }}</td>
                        <td>{{ ingredient.quantity }}</td>
                        <td>{{ ingredient.unit }}</td>
                        <td class="price">${{ ingredient.price_per_unit|stringformat:".2f" }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>

        <hr/>

        <div>
            <h2>Purchases</h2>
            <table class="inventory-table">
                <thead>
                    <tr>
                        <th>Menu Item</th>
                        <th>Price</th>
                        <th>Time</th>
                    </tr>
                </thead>
                <tbody>
                {% for purchase in purchases %}
                    <tr>
                        <td>{{ purchase.menu_item.title }}</td>
                        <td class="price">${{ purchase.menu_item.price|stringformat:".2f" }}</td>
                        <td>{{ purchase.timestamp }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>

        <hr/>

        <div>
            <h2>Menu</h2>
            <ul class="menu-items">
            {% for menu_item in menu_items %}
                <li>
                    <div class="menu-item-header">
                        <div class="menu-item-title">{{ menu_item.title }}</div>
                        <div class="menu-item-price">${{ menu_item.price|stringformat:".2f" }}</div>
                    </div>
                    <ul class="menu-item-ingredients">
                        {% for recipe_requirement in menu_item.reciperequirement_set.all %}
                        <li>{{ recipe_requirement.quantity }} {{recipe_requirement.ingredient.unit }} {{ recipe_requirement.ingredient.name }}</li>
                        {% endfor %}
                    </ul>
                </li>
            {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}

myrestaurant/inventory/templates/inventory/ingredients_list.html
{% extends 'base.html' %}
{% load static %} 
{% block title %}Django Delights{% endblock %}
{% block head %}
{% endblock %}
{% block content %}
    <h2>Ingredients</h2>
    <a href="{% url 'add_ingredient' %} ">Add New Ingredient to Inventory</a>
    <hr/>
    <table class="inventory-table">
        <thead>
            <tr>
                <th>Name</th>
                <th>Quantity</th>
                <th>Unit</th>
                <th>Unit Price</th>
            </tr>
        </thead>
        <tbody>
        {% for ingredient in object_list %}
            <tr>
                <td>
                    <a href="{% url "update_ingredient" ingredient.id %}">{{ ingredient.name }}</a>
                </td>
                <td>{{ ingredient.quantity }}</td>
                <td>{{ ingredient.unit }}</td>
                <td class="price">${{ ingredient.price_per_unit|stringformat:".2f" }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

myrestaurant/inventory/templates/inventory/menu_list.html
{% extends 'base.html' %}
{% load static %} 
{% block title %}Django Delights{% endblock %}
{% block head %}
{% endblock %}
{% block content %}
    <h2>Menu</h2>
    <p><a href="{% url 'add_menu_item' %}">Add New Item to Menu</a></p>
    <p><a href="{% url 'add_recipe_requirement' %}">Add Recipe Requirement for an Existing Menu Item</a></p>
    <hr/>
    <ul class="menu-items">
    {% for menu_item in object_list %}
        <li>
            <div class="menu-item-header">
                <div class="menu-item-title">{{ menu_item.title }}</div>
                <div class="menu-item-price">${{ menu_item.price|stringformat:".2f" }}</div>
            </div>
            <ul class="menu-item-ingredients">
                {% for recipe_requirement in menu_item.reciperequirement_set.all %}
                <li>{{ recipe_requirement.quantity }} {{recipe_requirement.ingredient.unit }} {{ recipe_requirement.ingredient.name }}</li>
                {% endfor %}
            </ul>
        </li>
    {% endfor %}
    </ul>
{% endblock %}

myrestaurant/inventory/templates/inventory/purchase_list.html
{% extends 'base.html' %}
{% load static %} 
{% block head %}
{% endblock %}
{% block content %}
    <h2>Purchases</h2>
    <a href="{% url 'add_purchase' %}">Record New Purchase</a>
    <hr/>
    <table class="inventory-table">
        <thead>
            <tr>
                <th>Menu Item</th>
                <th>Price</th>
                <th>Time</th>
            </tr>
        </thead>
        <tbody>
        {% for purchase in object_list %}
            <tr>
                <td>{{ purchase.menu_item.title }}</td>
                <td class="price">${{ purchase.menu_item.price|stringformat:".2f" }}</td>
                <td>{{ purchase.timestamp }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

myrestaurant/inventory/templates/inventory/reports.html
{% extends 'base.html' %}
{% load static %} 
{% block head %}
{% endblock %}
{% block content %}
    <h2>Purchases</h2>
    <table class="inventory-table">
        <thead>
            <tr>
                <th>Menu Item</th>
                <th>Price</th>
                <th>Time</th>
            </tr>
        </thead>
        <tbody>
        {% for purchase in purchases %}
            <tr>
                <td>{{ purchase.menu_item.title }}</td>
                <td class="price">${{ purchase.menu_item.price|stringformat:".2f" }}</td>
                <td>{{ purchase.timestamp }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <hr/>
    <h2>Totals</h2>
    <div style="color: green;">Total Revenue: ${{ revenue|stringformat:".2f" }}</div>
    <div style="color: red;">Total Cost: ${{ total_cost|stringformat:".2f" }}</div>
    <div style="color: blue;">Total Profit: ${{ profit|stringformat:".2f" }}</div>
{% endblock %}

myrestaurant/inventory/templates/inventory/update_ingredient.html
{% extends 'base.html' %}
{% load static %} 
{% block content %}
    <h2>Update Ingredient in Inventory</h2>
    <form method="post" class="flex-form">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Update"/>
    </form>
{% endblock %}